2019-09-04 16:34:20,848 ERROR: Exception on /index [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 35, in index
    prev_url=prev_url)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 47, in block "content"
    {% block blog_content %}{% endblock %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 11, in block "blog_content"
    {% include 'post.html' %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\post.html", line 10, in top-level template code
    <a href="{{ url_for('/', id=post.id) }}">
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/' with values ['id']. Did you mean 'post' instead?
2019-09-04 16:35:38,891 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 16:50:12,400 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 16:51:32,768 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 16:52:29,043 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 16:55:09,101 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 16:55:11,030 ERROR: Exception on /post/2 [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 157, in post
    return render_template('idpost.html', post=post)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Dreamcast\Documents\blog\main\templates\idpost.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 47, in block "content"
    {% block blog_content %}{% endblock %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\idpost.html", line 27, in block "blog_content"
    {{ wtf.quick_form(form) }}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-09-04 16:59:36,039 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
