2019-09-04 14:39:58,051 ERROR: Exception on /1 [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 150, in post
    return render_template('index.html', posts=post)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 47, in block "content"
    {% block blog_content %}{% endblock %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 10, in block "blog_content"
    {% for post in posts %}
TypeError: 'Post' object is not iterable
2019-09-04 14:40:40,744 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:40:42,437 ERROR: Exception on /1 [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 150, in post
    return render_template('index.html', posts=post)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\base.html", line 47, in block "content"
    {% block blog_content %}{% endblock %}
  File "C:\Users\Dreamcast\Documents\blog\main\templates\index.html", line 10, in block "blog_content"
    {% for post in posts %}
TypeError: 'Post' object is not iterable
2019-09-04 14:40:58,001 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
